### ISSUE TITLE
Req & Use of Cases diagrams

### ISSUE THREAD

**Issue by MartaMolinaGutierrez** [MartaMolinaGutierrez/ISO2-2022-A04#1]
Make the requirement diagram and the basic use of case diagram (taking into account the assumptions made by the group).

- [x] Initial version of the requirements model and simplified use case diagram
- [ ] Requirements model and simplified use case diagram with applied changes according to [Iteration 0-Meeting2](https://github.com/MartaMolinaGutierrez/ISO2-2022-A04/wiki/Iteration-0)

**Comment by RaulBarbaRojas** [comment]
Added both diagrams, however, refinements must be made as soon as the doubts that are commented in [Iteration 0-Meeting 2](https://github.com/MartaMolinaGutierrez/ISO2-2022-A04/wiki/Iteration-0) are solved.

**Comment by RaulBarbaRojas** [comment]
Added modifications as they were commented in [Iteration 0-Meeting 3](https://github.com/MartaMolinaGutierrez/ISO2-2022-A04/wiki/Iteration-0). Simplified use case model should now be complete.

**Comment by MartaMolinaGutierrez** [comment]
We have to re-do the diagram following the client-server paradigm

**Comment by RaulBarbaRojas** [comment]
Added the new version of the diagram as discussed in [Iteration 0-Meeting 4](https://github.com/MartaMolinaGutierrez/ISO2-2022-A04/wiki/Iteration-0) . Now, we distinguish the different clients that are required in the whole system. A slight change can be applied as it was commented in the meeting (change regarding login)
