### ISSUE TITLE
UC6 - EMPLOYEE DOMAIN - Employee_MV_Controller (v0.4.0) 

### ISSUE THREAD

**Issue by RaulBarbaRojas** [MartaMolinaGutierrez/ISO2-2022-A04#68]
- [x] basic functionalities (v.0.1.0)
- [x] createScheduling (v.0.2.0)
- [x] obtainForecast (v.0.3.0)
- [x] selectPatients (v.0.4.0)

**Comment by marina-prieto** [comment]
Done by Marina and Raul
