### ISSUE TITLE
UC7 - SERVER DOMAIN - Server_Stats_Controller (v.0.3.0)

### ISSUE THREAD

**Issue by LuisJavierHorcajada** [MartaMolinaGutierrez/ISO2-2022-A04#89]
- [x] basic functionalities (v.0.1.0)
- [x] selectStatistic (v0.2.0)
- [x] obtainStatistic (v.0.3.0)

**Comment by elenamartincantero** [comment]
done by Raul, Marina, Luis Javier & Elena
