### ISSUE TITLE
UC7 - EMPLOYEE DOMAIN - Employee_Stats_Controller (v0.3.0)

### ISSUE THREAD

**Issue by LuisJavierHorcajada** [MartaMolinaGutierrez/ISO2-2022-A04#95]
- [x] basic functionalities (v0.1.0)
- [x] selectStatistic (v0.2.0)
- [x] obtainStatistic (v0.3.0)

**Comment by elenamartincantero** [comment]
done by Raul, Marina, Luis Javier & Elena
